// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACwbM_fWt6ck-4ZfFwNmpSlHutubYzhZI',
    appId: '1:912207064154:web:148a7070742e3e006bbc63',
    messagingSenderId: '912207064154',
    projectId: 'prueba-dfe12',
    authDomain: 'prueba-dfe12.firebaseapp.com',
    databaseURL: 'https://prueba-dfe12-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-dfe12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC99TbaZX1J6DqJAiqp2uehf0ZyFf0WJUk',
    appId: '1:912207064154:android:ef05c9cb8d0431826bbc63',
    messagingSenderId: '912207064154',
    projectId: 'prueba-dfe12',
    databaseURL: 'https://prueba-dfe12-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-dfe12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7hu0jQ6l95VlkhNpZLekz6hfw4paKSsk',
    appId: '1:912207064154:ios:090292e6cd1c36c36bbc63',
    messagingSenderId: '912207064154',
    projectId: 'prueba-dfe12',
    databaseURL: 'https://prueba-dfe12-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-dfe12.appspot.com',
    iosClientId: '912207064154-a73mp6eq1kph2gekt2pvik4jj5ba8vpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fwitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7hu0jQ6l95VlkhNpZLekz6hfw4paKSsk',
    appId: '1:912207064154:ios:24f928e9cca791146bbc63',
    messagingSenderId: '912207064154',
    projectId: 'prueba-dfe12',
    databaseURL: 'https://prueba-dfe12-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-dfe12.appspot.com',
    iosClientId: '912207064154-qtdnnjrhuao3f58jvmog86cctp6k0u4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.fwitter.RunnerTests',
  );
}
